SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE USERS;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;
TRUNCATE TABLE request_logs;
ALTER TABLE request_logs ALTER COLUMN ID RESTART WITH 1;
SET REFERENTIAL_INTEGRITY TRUE;



